# Install a role from the Ansible Galaxy
collections:
  - name: ansible.netcommon
  - name: ansible.posix
  - name: ansible.utils
  - name: ansible.windows
  - name: check_point.mgmt
  - name: cisco.aci
  - name: cisco.ios
  - name: community.crypto
  - name: community.docker
  - name: community.general
  - name: Community.Mysql
  - name: Community.Postgresql
  - name: community.vmware
  - name: community.windows
  - name: containers.podman
  - name: f5networks.f5_modules
  - name: netapp.ontap 
  - name: netbox.netbox
  - name: containers.podman
  - name: dellemc.openmanage
  - name: vmware.vmware_rest
  - name: lowlydba.sqlserver
