# Install a role from the Ansible Galaxy
collections:
  - name: ansible.netcommon
  - name: ansible.utils
  - name: ansible.windows
  - name: cisco.aci
  - name: cisco.ios
  - name: community.crypto
  - name: community.docker
  - name: community.general
  - name: community.vmware
  - name: community.windows
  - name: community.docker
  - name: check_point.mgmt
  - name: netapp.ontap 
  - name: netbox.netbox
  - name: containers.podman
  - name: dellemc.openmanage
  - name: vmware.vmware_rest
