# Install a role from the Ansible Galaxy
collections:
  - name: ansible.netcommon
  - name: ansible.posix
  - name: ansible.utils
  - name: ansible.windows
  - name: check_point.mgmt
  - name: cisco.aci
  - name: cisco.ios
  - name: cisco.ise
  - name: community.crypto
  - name: community.docker
  - name: community.general
  - name: community.vmware
  - name: community.windows
  - name: containers.podman
  - name: dellemc.openmanage
  - name: f5networks.f5_modules
  - name: fortinet.console
  - name: fortinet.fortios
  - name: fortinet.fortiswitch
  - name: fortinet.fortiweb
  - name: fortinet.fortimanager
  - name: junipernetworks.junos
  - name: aicrosoft.ad
  - name: netapp.ontap
  - name: netbox.netbox
  - name: paloaltonetworks.panos
  - name: vmware.vmware_rest
  - name: lowlydba.sqlserver
  - name: kubernetes.core
  - name: vmware.vmware
